import { useMemo } from "react"
import { Activity, Cpu, Database, MemoryStick, TriangleAlert } from "lucide-react"
import { useQuery } from "@tanstack/react-query"
import { api } from "../../api"

type Overview = { metrics: { cpu_percent: number; memory_used_mb: number; memory_total_mb: number; goroutines: number }; total_tasks: number; running_tasks: number; completed_tasks: number; failed_tasks: number; profiles: number; workspaces: number; usage_mode: string; usage_note: string; flows: { source: string; target: string; value: number }[] }

function Metric({ icon: Icon, label, value, note, tone = "#10e0dd" }: { icon: typeof Cpu; label: string; value: string; note: string; tone?: string }) {
  return <div className="rounded-xl border border-[#1e2430] bg-[#11151f] p-4"><div className="flex items-center gap-2 text-[10px] uppercase tracking-wider text-[#8b93a7]"><Icon className="size-3.5" style={{ color: tone }} />{label}</div><p className="mt-3 font-mono text-2xl font-semibold tabular-nums text-[#e6e9ef]">{value}</p><p className="mt-1 text-[10px] text-[#687187]">{note}</p></div>
}

export default function OverviewPage() {
  const overview = useQuery({ queryKey: ["overview"], queryFn: () => api<Overview>("/api/overview"), refetchInterval: 5000 })
  const data = overview.data
  const flows = useMemo(() => { const map = new Map<string, number>(); for (const f of data?.flows ?? []) map.set(f.target, (map.get(f.target) ?? 0) + f.value); return [...map.entries()].sort((a, b) => b[1] - a[1]) }, [data?.flows])
  if (overview.isLoading) return <div className="flex h-full items-center justify-center text-sm text-[#8b93a7]">Memuat overview…</div>
  if (overview.isError || !data) return <div className="flex h-full items-center justify-center text-sm text-[#ef6b73]">Gagal load overview: {(overview.error as Error)?.message}</div>
  const memory = data.metrics.memory_total_mb ? Math.round(data.metrics.memory_used_mb / data.metrics.memory_total_mb * 100) : 0
  return <div className="min-h-0 flex-1 overflow-y-auto bg-[#0b0e14] p-4 text-[#e6e9ef] md:p-6"><div className="mx-auto max-w-7xl"><div className="flex items-end justify-between"><div><p className="font-mono text-[10px] uppercase tracking-[.18em] text-[#10e0dd]">Hermes Runtime</p><h1 className="mt-1 text-xl font-semibold tracking-tight">Overview</h1><p className="mt-1 text-xs text-[#8b93a7]">Live system health, task throughput, and model activity.</p></div><span className="flex items-center gap-1.5 font-mono text-[10px] text-emerald-300"><i className="size-1.5 rounded-full bg-current" /> live · 5s</span></div>
    <div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Metric icon={Cpu} label="CPU usage" value={`${data.metrics.cpu_percent.toFixed(1)}%`} note={`${data.metrics.goroutines} goroutines`} /><Metric icon={MemoryStick} label="Memory" value={`${memory}%`} note={`${data.metrics.memory_used_mb} / ${data.metrics.memory_total_mb} MB`} tone="#a78bfa" /><Metric icon={Activity} label="Running tasks" value={String(data.running_tasks)} note={`${data.total_tasks} total tasks`} tone="#8fd14f" /><Metric icon={TriangleAlert} label="Failed tasks" value={String(data.failed_tasks)} note={`${data.completed_tasks} completed`} tone="#ef6b73" /></div>
    <div className="mt-3 grid gap-3 lg:grid-cols-[1.35fr_.65fr]"><section className="rounded-xl border border-[#1e2430] bg-[#11151f] p-4"><div className="flex items-center justify-between"><div><h2 className="text-sm font-semibold">Model / provider activity</h2><p className="mt-1 text-[10px] text-[#687187]">Sankey-style flow from Kanban tasks to active Hermes profiles.</p></div><span className="rounded border border-[#1e2430] px-2 py-1 font-mono text-[9px] text-[#8b93a7]">{data.usage_mode}</span></div><div className="mt-5 grid min-h-48 grid-cols-[100px_1fr_150px] items-center gap-4"><div className="space-y-3">{["Kanban", "Running", "Completed", "Failed"].map((label, i) => <div key={label} className="rounded border border-[#1e2430] bg-[#0b0e14] px-2 py-2 text-center font-mono text-[10px]" style={{ color: ["#10e0dd", "#8fd14f", "#57d18d", "#ef6b73"][i] }}>{label}</div>)}</div><svg viewBox="0 0 220 180" className="h-48 w-full" role="img" aria-label="Task activity flow"><path d="M4 38 C70 38 80 30 150 30 M4 72 C70 72 80 70 150 70 M4 106 C70 106 80 110 150 110 M4 140 C70 140 80 150 150 150" fill="none" stroke="#10e0dd" strokeOpacity=".3" strokeWidth="10" /><path d="M4 38 C70 38 80 30 150 30 M4 72 C70 72 80 70 150 70 M4 106 C70 106 80 110 150 110 M4 140 C70 140 80 150 150 150" fill="none" stroke="#10e0dd" strokeOpacity=".8" strokeWidth="2" /></svg><div className="space-y-3">{flows.length ? flows.slice(0, 4).map(([name, value]) => <div key={name} className="flex items-center justify-between rounded border border-[#1e2430] bg-[#0b0e14] px-2 py-2 font-mono text-[10px]"><span className="truncate text-[#8b93a7]">{name}</span><b className="ml-2 text-[#e6e9ef]">{value}</b></div>) : <div className="rounded border border-dashed border-[#1e2430] px-2 py-4 text-center font-mono text-[10px] text-[#687187]">no profile activity</div>}</div></div><p className="text-[10px] text-[#687187]">{data.usage_note}</p></section><section className="rounded-xl border border-[#1e2430] bg-[#11151f] p-4"><h2 className="text-sm font-semibold">Runtime snapshot</h2><div className="mt-4 space-y-3 text-xs"><div className="flex justify-between border-b border-[#1e2430] pb-3"><span className="text-[#8b93a7]">Profiles</span><b>{data.profiles}</b></div><div className="flex justify-between border-b border-[#1e2430] pb-3"><span className="text-[#8b93a7]">Workspaces</span><b>{data.workspaces}</b></div><div><div className="mb-1 flex justify-between text-[10px] text-[#8b93a7]"><span>Memory pressure</span><span>{memory}%</span></div><div className="h-1.5 rounded bg-[#0b0e14]"><div className="h-full rounded bg-[#a78bfa]" style={{ width: `${Math.min(100, memory)}%` }} /></div></div></div><div className="mt-6 flex items-center gap-2 text-[10px] text-[#687187]"><Database className="size-3.5" />Live data from Hermes API</div></section></div></div></div>
}
